version: '3'

services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mymariadb
    ports:
      - 3306
    env_file:
      - .env
    networks:
      - my_network_1
    volumes:
      - mariadb_data:/var/lib/mysql    

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    container_name: mywordpress
    ports:
      - 9000
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - my_network_1
  
  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: mynginx
    ports:
      - 433:433
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - my_network_1
    depends_on:
      - wordpress

#   wordpress_data:
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rlarabi/data/wordpress # for linux vm
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rlarabi/data/mariadb # for linux vm


networks:
  my_network_1:
    driver: bridge